defaults:
  - model: deepspeech
  - writer: wandb
  - metrics: inferencer
  - datasets: example_eval # we do not want to run inference on training data
  - dataloader: example
  - transforms: deepspeech_transforms
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  pad_id: 0
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)  device: auto # device name or "auto"
  save_path: "inference" # any name here, can be a dataset name
  seed: 42
  from_pretrained: null # path to the pretrained model
  device: auto
